START TRANSACTION;

CREATE EXTENSION "uuid-ossp";

CREATE TABLE IF NOT EXISTS calendar (
    id    UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    date  TEXT NOT NULL,
    event TEXT NOT NULL
);

COMMIT;
