// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockstorageI is a mock of storageI interface.
type MockstorageI struct {
	ctrl     *gomock.Controller
	recorder *MockstorageIMockRecorder
}

// MockstorageIMockRecorder is the mock recorder for MockstorageI.
type MockstorageIMockRecorder struct {
	mock *MockstorageI
}

// NewMockstorageI creates a new mock instance.
func NewMockstorageI(ctrl *gomock.Controller) *MockstorageI {
	mock := &MockstorageI{ctrl: ctrl}
	mock.recorder = &MockstorageIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstorageI) EXPECT() *MockstorageIMockRecorder {
	return m.recorder
}
